class Image
  attr_reader :tag1, :tag2, :tag3, :image_url
  
  def initialize 
    @tag1 = IMAGE_TAGS.sample
    @tag2 = IMAGE_TAGS.sample
    @tag3 = IMAGE_TAGS.sample
  end
  
  def google_image_search
    uri = URI.parse("https://www.googleapis.com/customsearch/v1?q=#{tag1}+#{tag2}+#{tag3}&cx=012359143950802216498%3Arwlft0thadk&searchType=image&key=#{ENV['GOOGLE_CUSTOM_SEARCH_KEY']}")
    response = Net::HTTP.get_response(uri)
    query = JSON.parse(response.body)
    @image_url = query['items'][rand(10)]['link']
  end
  
  
  IMAGE_TAGS = [
            food,   
            foodporn, 
            foodie, 
            yummie, 
            nom, 
            nomnom, 
            hungry, 
            cleaneating, 
            healthy, 
            delish, 
            paleo, 
            wine, 
            vegan, 
            vegetarian, 
            italian, 
            pizza, 
            chinese, 
            sushi, 
            organic, 
            organicfood, 
            breakfast, 
            lunch, 
            dinner, 
            dessert, 
            foodgasm, 
            love, 
            instagood, 
            tbt, 
            photooftheday, 
            cute, 
            me, 
            beautiful, 
            happy, 
            follow, 
            followme, 
            picoftheday, 
            fashion, 
            selfie, 
            tagforlikes, 
            summer, 
            girl, 
            friends, 
            fun, 
            instadaily, 
            like, 
            smile, 
            like4like, 
            igers, 
            instamood, 
            food, 
            instalike, 
            family, 
            nofilter, 
            repost, 
            amazing, 
            bestoftheday, 
            art, 
            likeforlike, 
            style, 
            life, 
            nature, 
            swag, 
            follow4follow, 
            sun, 
            instagram, 
            pretty, 
            vscocam, 
            tflers, 
            sky, 
            beach, 
            beauty,
            lol, 
            fitness, 
            music, 
            followforfollow, 
            hair, 
            f4f, 
            party, 
            iphoneonly, 
            cool, 
            dog, 
            girls, 
            webstagram, 
            l4l, 
            photo, 
            sunset, 
            funny, 
            iphonesia, 
            night, 
            baby, 
            instasize, 
            tweegram, 
            my, 
            cat, 
            hot, 
            foodporn, 
            pink, 
            black, 
            vsco,
            blue,
            social,
            branding,
            socialmedia, 
            sales, 
            entrepreneur, 
            entrepreneurship, 
            marketing, 
            branding, 
            tech, 
            business, 
            contestalert, 
            sweepstakes, 
            giveaway, 
            discount, 
            travel, 
            deal, 
            smallbiz, 
            success
  ]
end